apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: kk5v6sd4k-nodejs 
  janus-idp.io/tekton: kk5v6sd4k-nodejs
  backstage.io/kubernetes-id: kk5v6sd4k-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: kk5v6sd4k-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml