apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: kk5v6sd4k-nodejs
  janus-idp.io/tekton: kk5v6sd4k-nodejs
  backstage.io/kubernetes-id: kk5v6sd4k-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: kk5v6sd4k-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
