apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: kk5v6sd4k-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kk5v6sd4k-nodejs 
  name: kk5v6sd4k-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: kk5v6sd4k-nodejs 
